language: python
sudo: no

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20

before_install:
  - sudo apt-get -qq update

install:
  - pip install tox

script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  pip: true

